### ISSUE TITLE
Currency Convert

### ISSUE THREAD

**Issue by AlexyKotliar** [phonix375/Pro-Trader#7]
Find and test an API for currency conversion, and make a function to convert all display amounts to the user-selected currency.

**Comment by BillieH88** [comment]
Changed some code in the script to make it easier for me to add my converter ... still going

**Comment by AlexyKotliar** [comment]
looking to see the result

**Comment by BillieH88** [comment]
![Capture2](https://user-images.githubusercontent.com/78821644/113657394-d8ecd980-966b-11eb-996b-6d9c60de3811.JPG)

![Capture](https://user-images.githubusercontent.com/78821644/113657410-e013e780-966b-11eb-9da8-f104cd20047a.JPG)
